// <auto-generated />
using System;
using EVF.DAL.DataConnection.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EVF.DAL.Migrations.Identity
{
    [DbContext(typeof(IdentityContext))]
    [Migration("20240124135822_AddIdPersonnelColumnInIdentityTable")]
    partial class AddIdPersonnelColumnInIdentityTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ArticleDivision", b =>
                {
                    b.Property<int>("IdArticle")
                        .HasColumnType("int");

                    b.Property<int>("IdDivision")
                        .HasColumnType("int");

                    b.HasKey("IdArticle", "IdDivision");

                    b.HasIndex("IdDivision");

                    b.ToTable("ArticleDivision");
                });

            modelBuilder.Entity("EVF.DAL.Entity.EVF.Article", b =>
                {
                    b.Property<int>("IdArticle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdArticle"));

                    b.Property<string>("CodeSap")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CodeSAP");

                    b.Property<int?>("IdType")
                        .HasColumnType("int");

                    b.Property<string>("Unite")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdArticle");

                    b.ToTable("Article");
                });

            modelBuilder.Entity("EVF.DAL.Entity.EVF.Client", b =>
                {
                    b.Property<int>("IdClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdClient"));

                    b.Property<string>("CodeSap")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CodeSAP");

                    b.Property<string>("Isopays")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ISOPays");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdClient");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("EVF.DAL.Entity.EVF.Division", b =>
                {
                    b.Property<int>("IdDivision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDivision"));

                    b.Property<string>("CodeDivision")
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("varchar(4)");

                    b.Property<int?>("IdSociete")
                        .HasColumnType("int");

                    b.HasKey("IdDivision");

                    b.HasIndex("IdSociete");

                    b.ToTable("Division");
                });

            modelBuilder.Entity("EVF.DAL.Entity.EVF.LibelleArticle", b =>
                {
                    b.Property<int>("IdLibelleArticle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLibelleArticle"));

                    b.Property<string>("CodeLangue")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("IdArticle")
                        .HasColumnType("int");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdLibelleArticle");

                    b.HasIndex("IdArticle");

                    b.ToTable("LibelleArticle");
                });

            modelBuilder.Entity("EVF.DAL.Entity.EVF.Personnel", b =>
                {
                    b.Property<int>("IdPersonnel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPersonnel"));

                    b.Property<string>("CodeSap")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CodeSAP");

                    b.Property<string>("Email")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("IdRole")
                        .HasColumnType("int");

                    b.Property<int?>("IdSociete")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdPersonnel");

                    b.HasIndex("IdSociete");

                    b.ToTable("Personnel");
                });

            modelBuilder.Entity("EVF.DAL.Entity.EVF.Prevision", b =>
                {
                    b.Property<int>("IdPrevision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPrevision"));

                    b.Property<string>("Annee")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("date");

                    b.Property<int>("IdArticle")
                        .HasColumnType("int");

                    b.Property<int>("IdClient")
                        .HasColumnType("int");

                    b.Property<int>("IdCommercial")
                        .HasColumnType("int");

                    b.Property<string>("Mois")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Volume")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("IdPrevision");

                    b.HasIndex("IdArticle");

                    b.HasIndex("IdClient");

                    b.HasIndex("IdCommercial");

                    b.ToTable("Prevision");
                });

            modelBuilder.Entity("EVF.DAL.Entity.EVF.Societe", b =>
                {
                    b.Property<int>("IdSociete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSociete"));

                    b.Property<string>("CodeLangue")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CodeSociete")
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("varchar(4)");

                    b.Property<string>("NomSociete")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("OrgCommerciale")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdSociete");

                    b.ToTable("Societe");
                });

            modelBuilder.Entity("EVF.DAL.Entity.EVF.SocieteClient", b =>
                {
                    b.Property<int>("IdSociete")
                        .HasColumnType("int");

                    b.Property<int>("IdClient")
                        .HasColumnType("int");

                    b.Property<int>("IdAssistantCommercial")
                        .HasColumnType("int");

                    b.Property<int>("IdCommercial")
                        .HasColumnType("int");

                    b.HasKey("IdSociete", "IdClient");

                    b.HasIndex("IdAssistantCommercial");

                    b.HasIndex("IdClient");

                    b.HasIndex("IdCommercial");

                    b.ToTable("SocieteClient");
                });

            modelBuilder.Entity("EVF.DAL.Entity.EVF.VentePortefeuille", b =>
                {
                    b.Property<int>("IdVentePort")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVentePort"));

                    b.Property<string>("Annee")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<int>("IdArticle")
                        .HasColumnType("int");

                    b.Property<int>("IdClient")
                        .HasColumnType("int");

                    b.Property<int>("IdCommercial")
                        .HasColumnType("int");

                    b.Property<string>("Mois")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<bool>("TypeVentePort")
                        .HasColumnType("bit");

                    b.Property<string>("Volume")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("IdVentePort");

                    b.HasIndex("IdArticle");

                    b.HasIndex("IdClient");

                    b.HasIndex("IdCommercial");

                    b.ToTable("VentePortefeuille");
                });

            modelBuilder.Entity("EVF.DAL.Entity.Identity.UserInfo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int?>("IdPersonnel")
                        .HasColumnType("int");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("IdPersonnel");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "e57be925-ce74-47b0-b975-034e7961958b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fbfeff00-b928-412c-934d-90ccabd1294c",
                            Email = "moni@gmail.com",
                            EmailConfirmed = false,
                            IdPersonnel = 4,
                            LockoutEnabled = false,
                            NormalizedEmail = "MONI@GMAIL.COM",
                            NormalizedUserName = "MONICA00",
                            PasswordHash = "AQAAAAIAAYagAAAAEHxRFs/fDcvMOkIYGEyVV+mnKhiim4O9qJfPsQ6GsYS3B2JnTE7+YN5TdRalZJ2taA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d7f83670-df8a-4b46-bbae-69dd34fc4a34",
                            TwoFactorEnabled = false,
                            UserName = "MONICA00"
                        },
                        new
                        {
                            Id = "21244986-da1d-4d3c-ab31-4e23a57e44f3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8d069240-da38-4952-9909-b663f7f44d36",
                            Email = "arii@yahoo.com",
                            EmailConfirmed = false,
                            IdPersonnel = 10,
                            LockoutEnabled = false,
                            NormalizedEmail = "ARII@YAHOO.COM",
                            NormalizedUserName = "ARIA01",
                            PasswordHash = "AQAAAAIAAYagAAAAEPm7SLK6ujUydOq5xMwNeNjt/+GEGVfsnBLCT7uwMdLOZcNcR4XNHZ9s9CozJMs1sw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0b2a3d84-7171-4cd7-8037-04b445a599bd",
                            TwoFactorEnabled = false,
                            UserName = "ARIA01"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "Commercial",
                            NormalizedName = "CO"
                        },
                        new
                        {
                            Id = "2",
                            Name = "AssistantCommercial",
                            NormalizedName = "AC"
                        },
                        new
                        {
                            Id = "3",
                            Name = "Administrateur",
                            NormalizedName = "ADM"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "e57be925-ce74-47b0-b975-034e7961958b",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "21244986-da1d-4d3c-ab31-4e23a57e44f3",
                            RoleId = "2"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ArticleDivision", b =>
                {
                    b.HasOne("EVF.DAL.Entity.EVF.Article", null)
                        .WithMany()
                        .HasForeignKey("IdArticle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EVF.DAL.Entity.EVF.Division", null)
                        .WithMany()
                        .HasForeignKey("IdDivision")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EVF.DAL.Entity.EVF.Division", b =>
                {
                    b.HasOne("EVF.DAL.Entity.EVF.Societe", "IdSocieteNavigation")
                        .WithMany("Divisions")
                        .HasForeignKey("IdSociete");

                    b.Navigation("IdSocieteNavigation");
                });

            modelBuilder.Entity("EVF.DAL.Entity.EVF.LibelleArticle", b =>
                {
                    b.HasOne("EVF.DAL.Entity.EVF.Article", "IdArticleNavigation")
                        .WithMany("LibelleArticles")
                        .HasForeignKey("IdArticle");

                    b.Navigation("IdArticleNavigation");
                });

            modelBuilder.Entity("EVF.DAL.Entity.EVF.Personnel", b =>
                {
                    b.HasOne("EVF.DAL.Entity.EVF.Societe", "IdSocieteNavigation")
                        .WithMany("Personnel")
                        .HasForeignKey("IdSociete");

                    b.Navigation("IdSocieteNavigation");
                });

            modelBuilder.Entity("EVF.DAL.Entity.EVF.Prevision", b =>
                {
                    b.HasOne("EVF.DAL.Entity.EVF.Article", "IdArticleNavigation")
                        .WithMany("Previsions")
                        .HasForeignKey("IdArticle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EVF.DAL.Entity.EVF.Client", "IdClientNavigation")
                        .WithMany("Previsions")
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EVF.DAL.Entity.EVF.Personnel", "IdCommercialNavigation")
                        .WithMany("Previsions")
                        .HasForeignKey("IdCommercial")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdArticleNavigation");

                    b.Navigation("IdClientNavigation");

                    b.Navigation("IdCommercialNavigation");
                });

            modelBuilder.Entity("EVF.DAL.Entity.EVF.SocieteClient", b =>
                {
                    b.HasOne("EVF.DAL.Entity.EVF.Personnel", "IdAssistantCommercialNavigation")
                        .WithMany("SocieteClientIdAssistantCommercialNavigations")
                        .HasForeignKey("IdAssistantCommercial")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EVF.DAL.Entity.EVF.Client", "IdClientNavigation")
                        .WithMany("SocieteClients")
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EVF.DAL.Entity.EVF.Personnel", "IdCommercialNavigation")
                        .WithMany("SocieteClientIdCommercialNavigations")
                        .HasForeignKey("IdCommercial")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EVF.DAL.Entity.EVF.Societe", "IdSocieteNavigation")
                        .WithMany("SocieteClients")
                        .HasForeignKey("IdSociete")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdAssistantCommercialNavigation");

                    b.Navigation("IdClientNavigation");

                    b.Navigation("IdCommercialNavigation");

                    b.Navigation("IdSocieteNavigation");
                });

            modelBuilder.Entity("EVF.DAL.Entity.EVF.VentePortefeuille", b =>
                {
                    b.HasOne("EVF.DAL.Entity.EVF.Article", "IdArticleNavigation")
                        .WithMany("VentePortefeuilles")
                        .HasForeignKey("IdArticle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EVF.DAL.Entity.EVF.Client", "IdClientNavigation")
                        .WithMany("VentePortefeuilles")
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EVF.DAL.Entity.EVF.Personnel", "IdCommercialNavigation")
                        .WithMany("VentePortefeuilles")
                        .HasForeignKey("IdCommercial")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdArticleNavigation");

                    b.Navigation("IdClientNavigation");

                    b.Navigation("IdCommercialNavigation");
                });

            modelBuilder.Entity("EVF.DAL.Entity.Identity.UserInfo", b =>
                {
                    b.HasOne("EVF.DAL.Entity.EVF.Personnel", "PersonnelNav")
                        .WithMany()
                        .HasForeignKey("IdPersonnel");

                    b.Navigation("PersonnelNav");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("EVF.DAL.Entity.Identity.UserInfo", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("EVF.DAL.Entity.Identity.UserInfo", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EVF.DAL.Entity.Identity.UserInfo", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("EVF.DAL.Entity.Identity.UserInfo", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EVF.DAL.Entity.EVF.Article", b =>
                {
                    b.Navigation("LibelleArticles");

                    b.Navigation("Previsions");

                    b.Navigation("VentePortefeuilles");
                });

            modelBuilder.Entity("EVF.DAL.Entity.EVF.Client", b =>
                {
                    b.Navigation("Previsions");

                    b.Navigation("SocieteClients");

                    b.Navigation("VentePortefeuilles");
                });

            modelBuilder.Entity("EVF.DAL.Entity.EVF.Personnel", b =>
                {
                    b.Navigation("Previsions");

                    b.Navigation("SocieteClientIdAssistantCommercialNavigations");

                    b.Navigation("SocieteClientIdCommercialNavigations");

                    b.Navigation("VentePortefeuilles");
                });

            modelBuilder.Entity("EVF.DAL.Entity.EVF.Societe", b =>
                {
                    b.Navigation("Divisions");

                    b.Navigation("Personnel");

                    b.Navigation("SocieteClients");
                });
#pragma warning restore 612, 618
        }
    }
}
